# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Resolve-and-Build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Package Update
      run: swift package update
    - name: Package Resolve
      run: swift package resolve
    - name: Build in Release mode
      run: swift build -c release -Xswiftc -g
